/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __MPRIS_GDBUS_H__
#define __MPRIS_GDBUS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.mpris.MediaPlayer2 */

#define MPRIS_TYPE_MEDIA_PLAYER2 (mpris_media_player2_get_type ())
#define MPRIS_MEDIA_PLAYER2(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MPRIS_TYPE_MEDIA_PLAYER2, mprisMediaPlayer2))
#define MPRIS_IS_MEDIA_PLAYER2(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MPRIS_TYPE_MEDIA_PLAYER2))
#define MPRIS_MEDIA_PLAYER2_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), MPRIS_TYPE_MEDIA_PLAYER2, mprisMediaPlayer2Iface))

struct _mprisMediaPlayer2;
typedef struct _mprisMediaPlayer2 mprisMediaPlayer2;
typedef struct _mprisMediaPlayer2Iface mprisMediaPlayer2Iface;

struct _mprisMediaPlayer2Iface
{
  GTypeInterface parent_iface;


  gboolean (*handle_quit) (
    mprisMediaPlayer2 *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_raise) (
    mprisMediaPlayer2 *object,
    GDBusMethodInvocation *invocation);

  gboolean  (*get_can_quit) (mprisMediaPlayer2 *object);

  gboolean  (*get_can_raise) (mprisMediaPlayer2 *object);

  gboolean  (*get_can_set_fullscreen) (mprisMediaPlayer2 *object);

  const gchar * (*get_desktop_entry) (mprisMediaPlayer2 *object);

  gboolean  (*get_fullscreen) (mprisMediaPlayer2 *object);

  gboolean  (*get_has_track_list) (mprisMediaPlayer2 *object);

  const gchar * (*get_identity) (mprisMediaPlayer2 *object);

  const gchar *const * (*get_supported_mime_types) (mprisMediaPlayer2 *object);

  const gchar *const * (*get_supported_uri_schemes) (mprisMediaPlayer2 *object);

};

GType mpris_media_player2_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *mpris_media_player2_interface_info (void);
guint mpris_media_player2_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void mpris_media_player2_complete_raise (
    mprisMediaPlayer2 *object,
    GDBusMethodInvocation *invocation);

void mpris_media_player2_complete_quit (
    mprisMediaPlayer2 *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void mpris_media_player2_call_raise (
    mprisMediaPlayer2 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_call_raise_finish (
    mprisMediaPlayer2 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_call_raise_sync (
    mprisMediaPlayer2 *proxy,
    GCancellable *cancellable,
    GError **error);

void mpris_media_player2_call_quit (
    mprisMediaPlayer2 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_call_quit_finish (
    mprisMediaPlayer2 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_call_quit_sync (
    mprisMediaPlayer2 *proxy,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
gboolean mpris_media_player2_get_can_quit (mprisMediaPlayer2 *object);
void mpris_media_player2_set_can_quit (mprisMediaPlayer2 *object, gboolean value);

gboolean mpris_media_player2_get_fullscreen (mprisMediaPlayer2 *object);
void mpris_media_player2_set_fullscreen (mprisMediaPlayer2 *object, gboolean value);

gboolean mpris_media_player2_get_can_set_fullscreen (mprisMediaPlayer2 *object);
void mpris_media_player2_set_can_set_fullscreen (mprisMediaPlayer2 *object, gboolean value);

gboolean mpris_media_player2_get_can_raise (mprisMediaPlayer2 *object);
void mpris_media_player2_set_can_raise (mprisMediaPlayer2 *object, gboolean value);

gboolean mpris_media_player2_get_has_track_list (mprisMediaPlayer2 *object);
void mpris_media_player2_set_has_track_list (mprisMediaPlayer2 *object, gboolean value);

const gchar *mpris_media_player2_get_identity (mprisMediaPlayer2 *object);
gchar *mpris_media_player2_dup_identity (mprisMediaPlayer2 *object);
void mpris_media_player2_set_identity (mprisMediaPlayer2 *object, const gchar *value);

const gchar *mpris_media_player2_get_desktop_entry (mprisMediaPlayer2 *object);
gchar *mpris_media_player2_dup_desktop_entry (mprisMediaPlayer2 *object);
void mpris_media_player2_set_desktop_entry (mprisMediaPlayer2 *object, const gchar *value);

const gchar *const *mpris_media_player2_get_supported_uri_schemes (mprisMediaPlayer2 *object);
gchar **mpris_media_player2_dup_supported_uri_schemes (mprisMediaPlayer2 *object);
void mpris_media_player2_set_supported_uri_schemes (mprisMediaPlayer2 *object, const gchar *const *value);

const gchar *const *mpris_media_player2_get_supported_mime_types (mprisMediaPlayer2 *object);
gchar **mpris_media_player2_dup_supported_mime_types (mprisMediaPlayer2 *object);
void mpris_media_player2_set_supported_mime_types (mprisMediaPlayer2 *object, const gchar *const *value);


/* ---- */

#define MPRIS_TYPE_MEDIA_PLAYER2_PROXY (mpris_media_player2_proxy_get_type ())
#define MPRIS_MEDIA_PLAYER2_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MPRIS_TYPE_MEDIA_PLAYER2_PROXY, mprisMediaPlayer2Proxy))
#define MPRIS_MEDIA_PLAYER2_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MPRIS_TYPE_MEDIA_PLAYER2_PROXY, mprisMediaPlayer2ProxyClass))
#define MPRIS_MEDIA_PLAYER2_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MPRIS_TYPE_MEDIA_PLAYER2_PROXY, mprisMediaPlayer2ProxyClass))
#define MPRIS_IS_MEDIA_PLAYER2_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MPRIS_TYPE_MEDIA_PLAYER2_PROXY))
#define MPRIS_IS_MEDIA_PLAYER2_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MPRIS_TYPE_MEDIA_PLAYER2_PROXY))

typedef struct _mprisMediaPlayer2Proxy mprisMediaPlayer2Proxy;
typedef struct _mprisMediaPlayer2ProxyClass mprisMediaPlayer2ProxyClass;
typedef struct _mprisMediaPlayer2ProxyPrivate mprisMediaPlayer2ProxyPrivate;

struct _mprisMediaPlayer2Proxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  mprisMediaPlayer2ProxyPrivate *priv;
};

struct _mprisMediaPlayer2ProxyClass
{
  GDBusProxyClass parent_class;
};

GType mpris_media_player2_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (mprisMediaPlayer2Proxy, g_object_unref)
#endif

void mpris_media_player2_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
mprisMediaPlayer2 *mpris_media_player2_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
mprisMediaPlayer2 *mpris_media_player2_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void mpris_media_player2_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
mprisMediaPlayer2 *mpris_media_player2_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
mprisMediaPlayer2 *mpris_media_player2_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define MPRIS_TYPE_MEDIA_PLAYER2_SKELETON (mpris_media_player2_skeleton_get_type ())
#define MPRIS_MEDIA_PLAYER2_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MPRIS_TYPE_MEDIA_PLAYER2_SKELETON, mprisMediaPlayer2Skeleton))
#define MPRIS_MEDIA_PLAYER2_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MPRIS_TYPE_MEDIA_PLAYER2_SKELETON, mprisMediaPlayer2SkeletonClass))
#define MPRIS_MEDIA_PLAYER2_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MPRIS_TYPE_MEDIA_PLAYER2_SKELETON, mprisMediaPlayer2SkeletonClass))
#define MPRIS_IS_MEDIA_PLAYER2_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MPRIS_TYPE_MEDIA_PLAYER2_SKELETON))
#define MPRIS_IS_MEDIA_PLAYER2_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MPRIS_TYPE_MEDIA_PLAYER2_SKELETON))

typedef struct _mprisMediaPlayer2Skeleton mprisMediaPlayer2Skeleton;
typedef struct _mprisMediaPlayer2SkeletonClass mprisMediaPlayer2SkeletonClass;
typedef struct _mprisMediaPlayer2SkeletonPrivate mprisMediaPlayer2SkeletonPrivate;

struct _mprisMediaPlayer2Skeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  mprisMediaPlayer2SkeletonPrivate *priv;
};

struct _mprisMediaPlayer2SkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType mpris_media_player2_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (mprisMediaPlayer2Skeleton, g_object_unref)
#endif

mprisMediaPlayer2 *mpris_media_player2_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.mpris.MediaPlayer2.Player */

#define MPRIS_TYPE_MEDIA_PLAYER2_PLAYER (mpris_media_player2_player_get_type ())
#define MPRIS_MEDIA_PLAYER2_PLAYER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MPRIS_TYPE_MEDIA_PLAYER2_PLAYER, mprisMediaPlayer2Player))
#define MPRIS_IS_MEDIA_PLAYER2_PLAYER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MPRIS_TYPE_MEDIA_PLAYER2_PLAYER))
#define MPRIS_MEDIA_PLAYER2_PLAYER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), MPRIS_TYPE_MEDIA_PLAYER2_PLAYER, mprisMediaPlayer2PlayerIface))

struct _mprisMediaPlayer2Player;
typedef struct _mprisMediaPlayer2Player mprisMediaPlayer2Player;
typedef struct _mprisMediaPlayer2PlayerIface mprisMediaPlayer2PlayerIface;

struct _mprisMediaPlayer2PlayerIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_next) (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_open_uri) (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_Uri);

  gboolean (*handle_pause) (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_play) (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_play_pause) (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_previous) (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_seek) (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation,
    gint64 arg_Offset);

  gboolean (*handle_set_position) (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_TrackId,
    gint64 arg_Position);

  gboolean (*handle_stop) (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean  (*get_can_control) (mprisMediaPlayer2Player *object);

  gboolean  (*get_can_go_next) (mprisMediaPlayer2Player *object);

  gboolean  (*get_can_go_previous) (mprisMediaPlayer2Player *object);

  gboolean  (*get_can_pause) (mprisMediaPlayer2Player *object);

  gboolean  (*get_can_play) (mprisMediaPlayer2Player *object);

  gboolean  (*get_can_seek) (mprisMediaPlayer2Player *object);

  const gchar * (*get_loop_status) (mprisMediaPlayer2Player *object);

  gdouble  (*get_maximum_rate) (mprisMediaPlayer2Player *object);

  GVariant * (*get_metadata) (mprisMediaPlayer2Player *object);

  gdouble  (*get_minimum_rate) (mprisMediaPlayer2Player *object);

  const gchar * (*get_playback_status) (mprisMediaPlayer2Player *object);

  gint64  (*get_position) (mprisMediaPlayer2Player *object);

  gdouble  (*get_rate) (mprisMediaPlayer2Player *object);

  gboolean  (*get_shuffle) (mprisMediaPlayer2Player *object);

  gdouble  (*get_volume) (mprisMediaPlayer2Player *object);

  void (*seeked) (
    mprisMediaPlayer2Player *object,
    gint64 arg_Position);

};

GType mpris_media_player2_player_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *mpris_media_player2_player_interface_info (void);
guint mpris_media_player2_player_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void mpris_media_player2_player_complete_next (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void mpris_media_player2_player_complete_previous (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void mpris_media_player2_player_complete_pause (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void mpris_media_player2_player_complete_play_pause (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void mpris_media_player2_player_complete_stop (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void mpris_media_player2_player_complete_play (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void mpris_media_player2_player_complete_seek (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void mpris_media_player2_player_complete_set_position (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void mpris_media_player2_player_complete_open_uri (
    mprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void mpris_media_player2_player_emit_seeked (
    mprisMediaPlayer2Player *object,
    gint64 arg_Position);



/* D-Bus method calls: */
void mpris_media_player2_player_call_next (
    mprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_player_call_next_finish (
    mprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_player_call_next_sync (
    mprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void mpris_media_player2_player_call_previous (
    mprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_player_call_previous_finish (
    mprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_player_call_previous_sync (
    mprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void mpris_media_player2_player_call_pause (
    mprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_player_call_pause_finish (
    mprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_player_call_pause_sync (
    mprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void mpris_media_player2_player_call_play_pause (
    mprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_player_call_play_pause_finish (
    mprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_player_call_play_pause_sync (
    mprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void mpris_media_player2_player_call_stop (
    mprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_player_call_stop_finish (
    mprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_player_call_stop_sync (
    mprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void mpris_media_player2_player_call_play (
    mprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_player_call_play_finish (
    mprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_player_call_play_sync (
    mprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void mpris_media_player2_player_call_seek (
    mprisMediaPlayer2Player *proxy,
    gint64 arg_Offset,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_player_call_seek_finish (
    mprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_player_call_seek_sync (
    mprisMediaPlayer2Player *proxy,
    gint64 arg_Offset,
    GCancellable *cancellable,
    GError **error);

void mpris_media_player2_player_call_set_position (
    mprisMediaPlayer2Player *proxy,
    const gchar *arg_TrackId,
    gint64 arg_Position,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_player_call_set_position_finish (
    mprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_player_call_set_position_sync (
    mprisMediaPlayer2Player *proxy,
    const gchar *arg_TrackId,
    gint64 arg_Position,
    GCancellable *cancellable,
    GError **error);

void mpris_media_player2_player_call_open_uri (
    mprisMediaPlayer2Player *proxy,
    const gchar *arg_Uri,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_player_call_open_uri_finish (
    mprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_player_call_open_uri_sync (
    mprisMediaPlayer2Player *proxy,
    const gchar *arg_Uri,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *mpris_media_player2_player_get_playback_status (mprisMediaPlayer2Player *object);
gchar *mpris_media_player2_player_dup_playback_status (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_playback_status (mprisMediaPlayer2Player *object, const gchar *value);

const gchar *mpris_media_player2_player_get_loop_status (mprisMediaPlayer2Player *object);
gchar *mpris_media_player2_player_dup_loop_status (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_loop_status (mprisMediaPlayer2Player *object, const gchar *value);

gdouble mpris_media_player2_player_get_rate (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_rate (mprisMediaPlayer2Player *object, gdouble value);

gboolean mpris_media_player2_player_get_shuffle (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_shuffle (mprisMediaPlayer2Player *object, gboolean value);

GVariant *mpris_media_player2_player_get_metadata (mprisMediaPlayer2Player *object);
GVariant *mpris_media_player2_player_dup_metadata (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_metadata (mprisMediaPlayer2Player *object, GVariant *value);

gdouble mpris_media_player2_player_get_volume (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_volume (mprisMediaPlayer2Player *object, gdouble value);

gint64 mpris_media_player2_player_get_position (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_position (mprisMediaPlayer2Player *object, gint64 value);

gdouble mpris_media_player2_player_get_minimum_rate (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_minimum_rate (mprisMediaPlayer2Player *object, gdouble value);

gdouble mpris_media_player2_player_get_maximum_rate (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_maximum_rate (mprisMediaPlayer2Player *object, gdouble value);

gboolean mpris_media_player2_player_get_can_go_next (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_can_go_next (mprisMediaPlayer2Player *object, gboolean value);

gboolean mpris_media_player2_player_get_can_go_previous (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_can_go_previous (mprisMediaPlayer2Player *object, gboolean value);

gboolean mpris_media_player2_player_get_can_play (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_can_play (mprisMediaPlayer2Player *object, gboolean value);

gboolean mpris_media_player2_player_get_can_pause (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_can_pause (mprisMediaPlayer2Player *object, gboolean value);

gboolean mpris_media_player2_player_get_can_seek (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_can_seek (mprisMediaPlayer2Player *object, gboolean value);

gboolean mpris_media_player2_player_get_can_control (mprisMediaPlayer2Player *object);
void mpris_media_player2_player_set_can_control (mprisMediaPlayer2Player *object, gboolean value);


/* ---- */

#define MPRIS_TYPE_MEDIA_PLAYER2_PLAYER_PROXY (mpris_media_player2_player_proxy_get_type ())
#define MPRIS_MEDIA_PLAYER2_PLAYER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MPRIS_TYPE_MEDIA_PLAYER2_PLAYER_PROXY, mprisMediaPlayer2PlayerProxy))
#define MPRIS_MEDIA_PLAYER2_PLAYER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MPRIS_TYPE_MEDIA_PLAYER2_PLAYER_PROXY, mprisMediaPlayer2PlayerProxyClass))
#define MPRIS_MEDIA_PLAYER2_PLAYER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MPRIS_TYPE_MEDIA_PLAYER2_PLAYER_PROXY, mprisMediaPlayer2PlayerProxyClass))
#define MPRIS_IS_MEDIA_PLAYER2_PLAYER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MPRIS_TYPE_MEDIA_PLAYER2_PLAYER_PROXY))
#define MPRIS_IS_MEDIA_PLAYER2_PLAYER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MPRIS_TYPE_MEDIA_PLAYER2_PLAYER_PROXY))

typedef struct _mprisMediaPlayer2PlayerProxy mprisMediaPlayer2PlayerProxy;
typedef struct _mprisMediaPlayer2PlayerProxyClass mprisMediaPlayer2PlayerProxyClass;
typedef struct _mprisMediaPlayer2PlayerProxyPrivate mprisMediaPlayer2PlayerProxyPrivate;

struct _mprisMediaPlayer2PlayerProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  mprisMediaPlayer2PlayerProxyPrivate *priv;
};

struct _mprisMediaPlayer2PlayerProxyClass
{
  GDBusProxyClass parent_class;
};

GType mpris_media_player2_player_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (mprisMediaPlayer2PlayerProxy, g_object_unref)
#endif

void mpris_media_player2_player_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
mprisMediaPlayer2Player *mpris_media_player2_player_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
mprisMediaPlayer2Player *mpris_media_player2_player_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void mpris_media_player2_player_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
mprisMediaPlayer2Player *mpris_media_player2_player_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
mprisMediaPlayer2Player *mpris_media_player2_player_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define MPRIS_TYPE_MEDIA_PLAYER2_PLAYER_SKELETON (mpris_media_player2_player_skeleton_get_type ())
#define MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MPRIS_TYPE_MEDIA_PLAYER2_PLAYER_SKELETON, mprisMediaPlayer2PlayerSkeleton))
#define MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MPRIS_TYPE_MEDIA_PLAYER2_PLAYER_SKELETON, mprisMediaPlayer2PlayerSkeletonClass))
#define MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MPRIS_TYPE_MEDIA_PLAYER2_PLAYER_SKELETON, mprisMediaPlayer2PlayerSkeletonClass))
#define MPRIS_IS_MEDIA_PLAYER2_PLAYER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MPRIS_TYPE_MEDIA_PLAYER2_PLAYER_SKELETON))
#define MPRIS_IS_MEDIA_PLAYER2_PLAYER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MPRIS_TYPE_MEDIA_PLAYER2_PLAYER_SKELETON))

typedef struct _mprisMediaPlayer2PlayerSkeleton mprisMediaPlayer2PlayerSkeleton;
typedef struct _mprisMediaPlayer2PlayerSkeletonClass mprisMediaPlayer2PlayerSkeletonClass;
typedef struct _mprisMediaPlayer2PlayerSkeletonPrivate mprisMediaPlayer2PlayerSkeletonPrivate;

struct _mprisMediaPlayer2PlayerSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  mprisMediaPlayer2PlayerSkeletonPrivate *priv;
};

struct _mprisMediaPlayer2PlayerSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType mpris_media_player2_player_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (mprisMediaPlayer2PlayerSkeleton, g_object_unref)
#endif

mprisMediaPlayer2Player *mpris_media_player2_player_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.mpris.MediaPlayer2.TrackList */

#define MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST (mpris_media_player2_track_list_get_type ())
#define MPRIS_MEDIA_PLAYER2_TRACK_LIST(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST, mprisMediaPlayer2TrackList))
#define MPRIS_IS_MEDIA_PLAYER2_TRACK_LIST(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST))
#define MPRIS_MEDIA_PLAYER2_TRACK_LIST_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST, mprisMediaPlayer2TrackListIface))

struct _mprisMediaPlayer2TrackList;
typedef struct _mprisMediaPlayer2TrackList mprisMediaPlayer2TrackList;
typedef struct _mprisMediaPlayer2TrackListIface mprisMediaPlayer2TrackListIface;

struct _mprisMediaPlayer2TrackListIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_add_track) (
    mprisMediaPlayer2TrackList *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_Uri,
    const gchar *arg_AfterTrack,
    gboolean arg_SetAsCurrent);

  gboolean (*handle_get_tracks_metadata) (
    mprisMediaPlayer2TrackList *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *arg_TrackIds);

  gboolean (*handle_go_to) (
    mprisMediaPlayer2TrackList *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_TrackId);

  gboolean (*handle_remove_track) (
    mprisMediaPlayer2TrackList *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_TrackId);

  gboolean  (*get_can_edit_tracks) (mprisMediaPlayer2TrackList *object);

  const gchar *const * (*get_tracks) (mprisMediaPlayer2TrackList *object);

  void (*track_added) (
    mprisMediaPlayer2TrackList *object,
    GVariant *arg_Metadata,
    const gchar *arg_AfterTrack);

  void (*track_list_replaced) (
    mprisMediaPlayer2TrackList *object,
    const gchar *const *arg_Tracks,
    const gchar *arg_CurrentTrack);

  void (*track_metadata_changed) (
    mprisMediaPlayer2TrackList *object,
    const gchar *arg_TrackId,
    GVariant *arg_Metadata);

  void (*track_removed) (
    mprisMediaPlayer2TrackList *object,
    const gchar *arg_TrackId);

};

GType mpris_media_player2_track_list_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *mpris_media_player2_track_list_interface_info (void);
guint mpris_media_player2_track_list_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void mpris_media_player2_track_list_complete_get_tracks_metadata (
    mprisMediaPlayer2TrackList *object,
    GDBusMethodInvocation *invocation,
    GVariant *Metadata);

void mpris_media_player2_track_list_complete_add_track (
    mprisMediaPlayer2TrackList *object,
    GDBusMethodInvocation *invocation);

void mpris_media_player2_track_list_complete_remove_track (
    mprisMediaPlayer2TrackList *object,
    GDBusMethodInvocation *invocation);

void mpris_media_player2_track_list_complete_go_to (
    mprisMediaPlayer2TrackList *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void mpris_media_player2_track_list_emit_track_list_replaced (
    mprisMediaPlayer2TrackList *object,
    const gchar *const *arg_Tracks,
    const gchar *arg_CurrentTrack);

void mpris_media_player2_track_list_emit_track_added (
    mprisMediaPlayer2TrackList *object,
    GVariant *arg_Metadata,
    const gchar *arg_AfterTrack);

void mpris_media_player2_track_list_emit_track_removed (
    mprisMediaPlayer2TrackList *object,
    const gchar *arg_TrackId);

void mpris_media_player2_track_list_emit_track_metadata_changed (
    mprisMediaPlayer2TrackList *object,
    const gchar *arg_TrackId,
    GVariant *arg_Metadata);



/* D-Bus method calls: */
void mpris_media_player2_track_list_call_get_tracks_metadata (
    mprisMediaPlayer2TrackList *proxy,
    const gchar *const *arg_TrackIds,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_track_list_call_get_tracks_metadata_finish (
    mprisMediaPlayer2TrackList *proxy,
    GVariant **out_Metadata,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_track_list_call_get_tracks_metadata_sync (
    mprisMediaPlayer2TrackList *proxy,
    const gchar *const *arg_TrackIds,
    GVariant **out_Metadata,
    GCancellable *cancellable,
    GError **error);

void mpris_media_player2_track_list_call_add_track (
    mprisMediaPlayer2TrackList *proxy,
    const gchar *arg_Uri,
    const gchar *arg_AfterTrack,
    gboolean arg_SetAsCurrent,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_track_list_call_add_track_finish (
    mprisMediaPlayer2TrackList *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_track_list_call_add_track_sync (
    mprisMediaPlayer2TrackList *proxy,
    const gchar *arg_Uri,
    const gchar *arg_AfterTrack,
    gboolean arg_SetAsCurrent,
    GCancellable *cancellable,
    GError **error);

void mpris_media_player2_track_list_call_remove_track (
    mprisMediaPlayer2TrackList *proxy,
    const gchar *arg_TrackId,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_track_list_call_remove_track_finish (
    mprisMediaPlayer2TrackList *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_track_list_call_remove_track_sync (
    mprisMediaPlayer2TrackList *proxy,
    const gchar *arg_TrackId,
    GCancellable *cancellable,
    GError **error);

void mpris_media_player2_track_list_call_go_to (
    mprisMediaPlayer2TrackList *proxy,
    const gchar *arg_TrackId,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris_media_player2_track_list_call_go_to_finish (
    mprisMediaPlayer2TrackList *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris_media_player2_track_list_call_go_to_sync (
    mprisMediaPlayer2TrackList *proxy,
    const gchar *arg_TrackId,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *const *mpris_media_player2_track_list_get_tracks (mprisMediaPlayer2TrackList *object);
gchar **mpris_media_player2_track_list_dup_tracks (mprisMediaPlayer2TrackList *object);
void mpris_media_player2_track_list_set_tracks (mprisMediaPlayer2TrackList *object, const gchar *const *value);

gboolean mpris_media_player2_track_list_get_can_edit_tracks (mprisMediaPlayer2TrackList *object);
void mpris_media_player2_track_list_set_can_edit_tracks (mprisMediaPlayer2TrackList *object, gboolean value);


/* ---- */

#define MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST_PROXY (mpris_media_player2_track_list_proxy_get_type ())
#define MPRIS_MEDIA_PLAYER2_TRACK_LIST_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST_PROXY, mprisMediaPlayer2TrackListProxy))
#define MPRIS_MEDIA_PLAYER2_TRACK_LIST_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST_PROXY, mprisMediaPlayer2TrackListProxyClass))
#define MPRIS_MEDIA_PLAYER2_TRACK_LIST_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST_PROXY, mprisMediaPlayer2TrackListProxyClass))
#define MPRIS_IS_MEDIA_PLAYER2_TRACK_LIST_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST_PROXY))
#define MPRIS_IS_MEDIA_PLAYER2_TRACK_LIST_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST_PROXY))

typedef struct _mprisMediaPlayer2TrackListProxy mprisMediaPlayer2TrackListProxy;
typedef struct _mprisMediaPlayer2TrackListProxyClass mprisMediaPlayer2TrackListProxyClass;
typedef struct _mprisMediaPlayer2TrackListProxyPrivate mprisMediaPlayer2TrackListProxyPrivate;

struct _mprisMediaPlayer2TrackListProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  mprisMediaPlayer2TrackListProxyPrivate *priv;
};

struct _mprisMediaPlayer2TrackListProxyClass
{
  GDBusProxyClass parent_class;
};

GType mpris_media_player2_track_list_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (mprisMediaPlayer2TrackListProxy, g_object_unref)
#endif

void mpris_media_player2_track_list_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
mprisMediaPlayer2TrackList *mpris_media_player2_track_list_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
mprisMediaPlayer2TrackList *mpris_media_player2_track_list_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void mpris_media_player2_track_list_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
mprisMediaPlayer2TrackList *mpris_media_player2_track_list_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
mprisMediaPlayer2TrackList *mpris_media_player2_track_list_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST_SKELETON (mpris_media_player2_track_list_skeleton_get_type ())
#define MPRIS_MEDIA_PLAYER2_TRACK_LIST_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST_SKELETON, mprisMediaPlayer2TrackListSkeleton))
#define MPRIS_MEDIA_PLAYER2_TRACK_LIST_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST_SKELETON, mprisMediaPlayer2TrackListSkeletonClass))
#define MPRIS_MEDIA_PLAYER2_TRACK_LIST_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST_SKELETON, mprisMediaPlayer2TrackListSkeletonClass))
#define MPRIS_IS_MEDIA_PLAYER2_TRACK_LIST_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST_SKELETON))
#define MPRIS_IS_MEDIA_PLAYER2_TRACK_LIST_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MPRIS_TYPE_MEDIA_PLAYER2_TRACK_LIST_SKELETON))

typedef struct _mprisMediaPlayer2TrackListSkeleton mprisMediaPlayer2TrackListSkeleton;
typedef struct _mprisMediaPlayer2TrackListSkeletonClass mprisMediaPlayer2TrackListSkeletonClass;
typedef struct _mprisMediaPlayer2TrackListSkeletonPrivate mprisMediaPlayer2TrackListSkeletonPrivate;

struct _mprisMediaPlayer2TrackListSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  mprisMediaPlayer2TrackListSkeletonPrivate *priv;
};

struct _mprisMediaPlayer2TrackListSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType mpris_media_player2_track_list_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (mprisMediaPlayer2TrackListSkeleton, g_object_unref)
#endif

mprisMediaPlayer2TrackList *mpris_media_player2_track_list_skeleton_new (void);


G_END_DECLS

#endif /* __MPRIS_GDBUS_H__ */
